apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gp-ivolve-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shimaa-esmat/CloudDevOpsProject.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
